server:
  port: 9001

spring:
  application:
    name: xdclass-user-service

#redis配置
  redis:
    host: 139.159.157.112
    password: 123456
    port: 8000

#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xyclass_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: qq2711601

  #邮箱服务配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: 15219019995@163.com #发送邮件的邮箱地址
    password: GJHKBIPLFLWKQMUD #客户端授权码，不是邮箱密码,网易的是自己设置的
    default-encoding: utf-8
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO